from util.Enum import Enum

pIndex = Enum(["Name", "Description", "Default", "ColorList","RequiredColors","PWM"])
Colors = Enum(["Red", "Red-Orange", "Cyan", "Green", "Blue", "White", "Yellow","Empty"])
ColorsByIndex = ["Red", "Red-Orange", "Cyan", "Green", "Blue", "White", "Yellow","Empty"]

DEFAULT_PATTERNS = list()

# Color List MUST be initialized

pattern_zero = list()
pattern_zero.append("Pattern One")
pattern_zero.append( "Pattern One Description")
pattern_zero.append(True)
pattern_zero.append([ColorsByIndex[Colors.Empty]])
pattern_zero.append(1)
pattern_zero.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_zero)

pattern_one = list()
pattern_one.append("Pattern Two")
pattern_one.append("Pattern Two Description")
pattern_one.append(True)
pattern_one.append([ColorsByIndex[Colors.Empty], ColorsByIndex[Colors.Empty]])
pattern_one.append(2)
pattern_one.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_one)

pattern_two = list()
pattern_two.append("Pattern Three")
pattern_two.append("Pattern Three Description")
pattern_two.append(True)
pattern_two.append([ColorsByIndex[Colors.Empty]])
pattern_two.append(1)
pattern_two.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_two)

pattern_three = list()
pattern_three.append("Pattern Four")
pattern_three.append("Pattern Four Description")
pattern_three.append(True)
pattern_three.append([ColorsByIndex[Colors.Empty]])
pattern_three.append(1)
pattern_three.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_three)

pattern_four = list()
pattern_four.append("Pattern Five")
pattern_four.append("Pattern Five Description")
pattern_four.append(True)
pattern_four.append([ColorsByIndex[Colors.Empty]])
pattern_four.append(1)
pattern_four.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_four)

pattern_five = list()
pattern_five.append("Pattern Six")
pattern_five.append("Pattern Six Description")
pattern_five.append(True)
pattern_five.append([ColorsByIndex[Colors.Empty],ColorsByIndex[Colors.Empty],ColorsByIndex[Colors.Empty]])
pattern_five.append(3)
pattern_five.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_five)

pattern_six = list()
pattern_six.append("Pattern Seven")
pattern_six.append("Pattern Seven Description")
pattern_six.append(True)
pattern_six.append([ColorsByIndex[Colors.Empty]])
pattern_six.append(1)
pattern_six.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_six)

pattern_seven = list()
pattern_seven.append("Pattern Eight")
pattern_seven.append("Pattern Eight Description")
pattern_seven.append(True)
pattern_seven.append([ColorsByIndex[Colors.Empty]])
pattern_seven.append(1)
pattern_seven.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_seven)

pattern_eight = list()
pattern_eight.append("Pattern Nine")
pattern_eight.append("Pattern Nine Description")
pattern_eight.append(True)
pattern_eight.append([ColorsByIndex[Colors.Empty]])
pattern_eight.append(1)
pattern_eight.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_eight)

pattern_nine = list()
pattern_nine.append("Pattern Ten")
pattern_nine.append("Pattern Ten Description")
pattern_nine.append(True)
pattern_nine.append([ColorsByIndex[Colors.Empty]])
pattern_nine.append(1)
pattern_nine.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_nine)

pattern_ten = list()
pattern_ten.append("Pattern Eleven")
pattern_ten.append("Pattern Eleven Description")
pattern_ten.append(True)
pattern_ten.append([ColorsByIndex[Colors.Empty]])
pattern_ten.append(1)
pattern_ten.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_ten)

pattern_eleven = list()
pattern_eleven.append("Pattern Twelve")
pattern_eleven.append("Pattern Twelve Description")
pattern_eleven.append(True)
pattern_eleven.append([ColorsByIndex[Colors.Empty]])
pattern_eleven.append(1)
pattern_eleven.append([[100,100,1],[150,150,1]])
DEFAULT_PATTERNS.append(pattern_eleven)

NUM_DEFAULT_PATTERNS = len(DEFAULT_PATTERNS)